In [1]:
import pandas as pd
import numpy as np

portsugro_df=pd.read_csv('Porto_Seguro_Sample_58k.csv')
portsugro_df

id  target  ps_ind_01  ps_ind_02_cat  ps_ind_03  ps_ind_04_cat  \
0           7       0          2              2          5              1   
1           9       0          1              1          7              0   
2          13       0          5              4          9              1   
3          16       0          0              1          2              0   
4          17       0          0              2          0              1   
...       ...     ...        ...            ...        ...            ...   
57994  145373       0          1              1          8              0   
57995  145378       0          7              1          9              1   
57996  145380       0          0              1          1              0   
57997  145382       0          2              2          1              1   
57998  145384       0          5              1          6              1   

       ps_ind_05_cat  ps_ind_06_bin  ps_ind_07_bin  ps_ind_08_bin  ...  \
0                  0              0              1              0  ...   
1                  0              0              0              1  ...   
2                  0              0              0              1  ...   
3                  0              1              0              0  ...   
4                  0              1              0              0  ...   
...              ...            ...            ...            ...  ...   
57994              0              1              0              0  ...   
57995              0              0              0              1  ...   
57996              0              0              0              1  ...   
57997              0              1              0              0  ...   
57998              0              1              0              0  ...   

       ps_calc_11  ps_calc_12  ps_calc_13  ps_calc_14  ps_calc_15_bin  \
0               9           1           5           8               0   
1               3           1           1           9               0   
2               4           2           7           7               0   
3               2           2           4           9               0   
4               3           1           1           3               0   
...           ...         ...         ...         ...             ...   
57994           6           4           3          10               0   
57995           5           0           2           9               0   
57996           9           3           2           8               0   
57997           7           0           5           6               0   
57998           6           3           0           6               0   

       ps_calc_16_bin  ps_calc_17_bin  ps_calc_18_bin  ps_calc_19_bin  \
0                   1               1               0               0   
1                   1               1               0               1   
2                   1               1               0               1   
3                   0               0               0               0   
4                   0               0               1               1   
...               ...             ...             ...             ...   
57994               1               1               0               0   
57995               0               0               0               0   
57996               1               0               0               1   
57997               1               0               0               1   
57998               1               0               1               1   

       ps_calc_20_bin  
0                   1  
1                   0  
2                   0  
3                   0  
4                   0  
...               ...  
57994               0  
57995               0  
57996               0  
57997               1  
57998               0  

[57999 rows x 59 columns]

In [2]:
portsugro_df=portsugro_df.replace(-1,np.NaN)

In [3]:
missing_valuesper=portsugro_df.isnull().sum()/portsugro_df.shape[0]*100

In [4]:
portsugro_df.drop(columns='ps_car_03_cat',inplace=True)

In [5]:
portsugro_df_id=portsugro_df['id']
y=portsugro_df['target']

In [6]:
portsugro_df.drop(columns=['id','target'],inplace=True)

In [7]:
portsugro_df.shape

(57999, 56)

In [8]:
cat=[]
reg=[]

for col in portsugro_df.columns:
    if 'cat' in col:
        cat.append(col)
    elif 'bin' in col:
        cat.append(col)
    elif 'reg' in col:
        reg.append(col)
    elif 'ind' in col:
        cat.append(col)
    elif portsugro_df[col].dtype=='float64':
        reg.append(col)
    else:
        cat.append(col)    

In [9]:
portsugro_df[cat]=portsugro_df[cat].astype('O')
portsugro_df[reg]=portsugro_df[reg].astype('float64')

In [10]:
portsugro_df[cat].head()

ps_ind_01 ps_ind_02_cat ps_ind_03 ps_ind_04_cat ps_ind_05_cat ps_ind_06_bin  \
0         2             2         5             1             0             0   
1         1             1         7             0             0             0   
2         5             4         9             1             0             0   
3         0             1         2             0             0             1   
4         0             2         0             1             0             1   

  ps_ind_07_bin ps_ind_08_bin ps_ind_09_bin ps_ind_10_bin  ... ps_calc_11  \
0             1             0             0             0  ...          9   
1             0             1             0             0  ...          3   
2             0             1             0             0  ...          4   
3             0             0             0             0  ...          2   
4             0             0             0             0  ...          3   

  ps_calc_12 ps_calc_13 ps_calc_14 ps_calc_15_bin ps_calc_16_bin  \
0          1          5          8              0              1   
1          1          1          9              0              1   
2          2          7          7              0              1   
3          2          4          9              0              0   
4          1          1          3              0              0   

  ps_calc_17_bin ps_calc_18_bin ps_calc_19_bin ps_calc_20_bin  
0              1              0              0              1  
1              1              0              1              0  
2              1              0              1              0  
3              0              0              0              0  
4              0              1              1              0  

[5 rows x 46 columns]

In [11]:
portsugro_df[reg]

ps_reg_01  ps_reg_02  ps_reg_03  ps_car_12  ps_car_13  ps_car_14  \
0            0.7        0.2   0.718070   0.400000   0.883679   0.370810   
1            0.8        0.4   0.766078   0.316228   0.618817   0.388716   
2            0.0        0.0        NaN   0.316228   0.641586   0.347275   
3            0.9        0.2   0.580948   0.374166   0.542949   0.294958   
4            0.7        0.6   0.840759   0.316070   0.565832   0.365103   
...          ...        ...        ...        ...        ...        ...   
57994        0.3        0.0   0.461655   0.316228   0.688002   0.361939   
57995        0.6        0.3   0.637377   0.316070   0.578756   0.365103   
57996        0.1        0.1        NaN   0.316228   0.677196   0.320156   
57997        0.7        0.3   0.817389   0.374166   0.817083   0.390768   
57998        0.9        0.4   0.962419   0.400000   0.643306   0.393700   

       ps_car_15  ps_calc_01  ps_calc_02  ps_calc_03  
0       3.605551         0.6         0.5         0.2  
1       2.449490         0.3         0.1         0.3  
2       3.316625         0.5         0.7         0.1  
3       2.000000         0.6         0.9         0.1  
4       2.000000         0.4         0.6         0.0  
...          ...         ...         ...         ...  
57994   3.464102         0.1         0.8         0.6  
57995   2.236068         0.3         0.9         0.0  
57996   3.000000         0.2         0.1         0.1  
57997   3.605551         0.4         0.4         0.6  
57998   2.236068         0.9         0.8         0.3  

[57999 rows x 10 columns]

In [12]:
rows,columns=portsugro_df.shape
drop_nunique_cols=[]
for col in portsugro_df.columns:
    if portsugro_df[col].nunique==rows or portsugro_df[col].nunique==1:
        drop_nunique_cols.append(col)
drop_nunique_cols

[]

In [13]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(portsugro_df,y,test_size=0.2,random_state=42)

# Filling missing values

for col in X_train.columns:
    if X_train[col].dtype=='object':
        X_train[col]=X_train[col].fillna(X_train[col].mode()[0]).astype(object)
        X_test[col]=X_test[col].fillna(X_train[col].mode()[0]).astype(object)
        
    else:
        X_train[col]=X_train[col].fillna(X_train[col].mean())
        X_test[col]=X_test[col].fillna(X_train[col].mean())



C:\Users\tejad\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\tejad\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\tejad\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = val

In [14]:
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')

class LabelEncoderExt(object):
    def __init__(self):
        """
        It differs from LabelEncoder by handling new classes and providing a value for it [Unknown]
        Unknown will be added in fit and transform will take care of new item. It gives unknown class id
        """
        self.label_encoder = LabelEncoder()
        # self.classes_ = self.label_encoder.classes_

    def fit(self, data_list):
        """
        This will fit the encoder for all the unique values and introduce unknown value
        :param data_list: A list of string
        :return: self
        """
        self.label_encoder = self.label_encoder.fit(list(data_list) + ['Unknown'])
        self.classes_ = self.label_encoder.classes_

        return self

    def transform(self, data_list):
        """
        This will transform the data_list to id list where the new values get assigned to Unknown class
        :param data_list:
        :return:
        """
        new_data_list = list(data_list)
        for unique_item in np.unique(data_list):
            if unique_item not in self.label_encoder.classes_:
                new_data_list = ['Unknown' if x==unique_item else x for x in new_data_list]

        return self.label_encoder.transform(new_data_list)
    
le=LabelEncoderExt()

for col in X_train.columns:
    if X_train[col].dtype=='object':
        le.fit(X_train[col])
        X_train[col]=le.transform(X_train[col])
        X_test[col]=le.transform(X_test[col])


In [15]:
from sklearn.preprocessing import MinMaxScaler
import warnings
warnings.filterwarnings('ignore')

mMS = MinMaxScaler()
for col in X_test.columns:
    X_train[col] = mMS.fit_transform(np.array(X_train[col]).reshape(-1,1))
    X_test[col] = mMS.transform(np.array(X_test[col]).reshape(-1,1))

In [16]:
from imblearn.over_sampling import SMOTE

In [17]:
print('Before OverSampling, the shape of train_X: {}'.format(X_train.shape)) 
print('Before OverSampling, the shape of train_y: {} \n'.format(y_train.shape)) 

print("Before OverSampling, counts of label '1': {}".format(sum(y_train == 1))) 
print("Before OverSampling, counts of label '0': {}".format(sum(y_train == 0))) 


Before OverSampling, the shape of train_X: (46399, 56)
Before OverSampling, the shape of train_y: (46399,) 

Before OverSampling, counts of label '1': 1704
Before OverSampling, counts of label '0': 44695


In [18]:
sm=SMOTE(sampling_strategy=0.3)
X_train_sm, y_train_sm = sm.fit_sample(X_train, y_train) 

                                 
print('After OverSampling, the shape of train_X: {}'.format(X_train_sm.shape)) 
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_sm.shape)) 

print("After OverSampling, counts of label '1': {}".format(sum(y_train_sm == 1))) 
print("After OverSampling, counts of label '0': {}".format(sum(y_train_sm == 0))) 


After OverSampling, the shape of train_X: (58103, 56)
After OverSampling, the shape of train_y: (58103,) 

After OverSampling, counts of label '1': 13408
After OverSampling, counts of label '0': 44695


In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import r2_score,mean_squared_error,recall_score,precision_score,f1_score,roc_auc_score,roc_curve,confusion_matrix

## Models after applying SMOTE

In [20]:
model={
    'LR':LogisticRegression(),
    'Randomforest':RandomForestClassifier(),
    'Decesiontree':DecisionTreeClassifier(),
    'adaboost':AdaBoostClassifier()
}

In [21]:
for mmodel,nmodel in model.items():
    
    obj=model[mmodel]
    obj.fit(X_train_sm,y_train_sm)
    y_predict=obj.predict(X_test)#got y_predict and test y_predict with y_test
    y_predict_proba=obj.predict_proba(X_test)[::,1]
    
    train_accuracy=obj.score(X_train_sm,y_train_sm)
    test_accuracy=obj.score(X_test,y_test)
    
    recallscore=recall_score(y_test, y_predict)
    precisionscore=precision_score(y_test, y_predict)
    
    f1score=f1_score(y_test,y_predict)    
    auc=roc_auc_score(y_test,y_predict_proba)
    fpr,tpr,thrshould=roc_curve(y_test,y_predict_proba)
    

    print("Model Name: ", mmodel)
    print("ConfusionMatrix-\n",confusion_matrix(y_test,y_predict))
    print('trainaccuracy---{}'.format(train_accuracy))
    print('testaccuracy----{}'.format(test_accuracy))
    print('recallscore-----{}'.format(recallscore))
    print('precisionscore--{}'.format(precisionscore))
    print('f1score---------{}'.format(f1score))
    print('roc_auc_score---{}'.format(auc))
    print("\n\n")



Model Name:  LR
ConfusionMatrix-
 [[11162    16]
 [  421     1]]
trainaccuracy---0.7684629020876719
testaccuracy----0.9623275862068965
recallscore-----0.002369668246445498
precisionscore--0.058823529411764705
f1score---------0.004555808656036447
roc_auc_score---0.6073846816571822



Model Name:  Randomforest
ConfusionMatrix-
 [[11176     2]
 [  422     0]]
trainaccuracy---1.0
testaccuracy----0.9634482758620689
recallscore-----0.0
precisionscore--0.0
f1score---------0.0
roc_auc_score---0.547831132412262



Model Name:  Decesiontree
ConfusionMatrix-
 [[10566   612]
 [  398    24]]
trainaccuracy---1.0
testaccuracy----0.9129310344827586
recallscore-----0.05687203791469194
precisionscore--0.03773584905660377
f1score---------0.045368620037807186
roc_auc_score---0.5010608176691012



Model Name:  adaboost
ConfusionMatrix-
 [[11134    44]
 [  421     1]]
trainaccuracy---0.871469631516445
testaccuracy----0.9599137931034483
recallscore-----0.002369668246445498
precisionscore--0.02222222222222222

# Models befor applying SMOTE

In [23]:
model={
    'LR':LogisticRegression(),
    'Randomforest':RandomForestClassifier(),
    'Decesiontree':DecisionTreeClassifier(),
    'adaboost':AdaBoostClassifier()
}

In [24]:
for mmodel,nmodel in model.items():
    
    obj=model[mmodel]
    obj.fit(X_train,y_train)
    y_predict=obj.predict(X_test)#got y_predict and test y_predict with y_test
    y_predict_proba=obj.predict_proba(X_test)[::,1]
    
    train_accuracy=obj.score(X_train,y_train)
    test_accuracy=obj.score(X_test,y_test)
    
    recallscore=recall_score(y_test, y_predict)
    precisionscore=precision_score(y_test, y_predict)
    
    f1score=f1_score(y_test,y_predict)    
    auc=roc_auc_score(y_test,y_predict_proba)
    fpr,tpr,thrshould=roc_curve(y_test,y_predict_proba)
    

    print("Model Name: ", mmodel)
    print("ConfusionMatrix-\n",confusion_matrix(y_test,y_predict))
    print('trainaccuracy---{}'.format(train_accuracy))
    print('testaccuracy----{}'.format(test_accuracy))
    print('recallscore-----{}'.format(recallscore))
    print('precisionscore--{}'.format(precisionscore))
    print('f1score---------{}'.format(f1score))
    print('roc_auc_score---{}'.format(auc))
    print("\n\n")



Model Name:  LR
ConfusionMatrix-
 [[11178     0]
 [  422     0]]
trainaccuracy---0.9632750705834178
testaccuracy----0.9636206896551724
recallscore-----0.0
precisionscore--0.0
f1score---------0.0
roc_auc_score---0.6057813714990261



Model Name:  Randomforest
ConfusionMatrix-
 [[11178     0]
 [  422     0]]
trainaccuracy---0.9999353434341257
testaccuracy----0.9636206896551724
recallscore-----0.0
precisionscore--0.0
f1score---------0.0
roc_auc_score---0.5321658403142937



Model Name:  Decesiontree
ConfusionMatrix-
 [[10669   509]
 [  401    21]]
trainaccuracy---1.0
testaccuracy----0.9215517241379311
recallscore-----0.04976303317535545
precisionscore--0.03962264150943396
f1score---------0.044117647058823525
roc_auc_score---0.502113579568533



Model Name:  adaboost
ConfusionMatrix-
 [[11178     0]
 [  422     0]]
trainaccuracy---0.9632750705834178
testaccuracy----0.9636206896551724
recallscore-----0.0
precisionscore--0.0
f1score---------0.0
roc_auc_score---0.5968189037539039



